#!/bin/bash

###INET_CHECK=`ping -c1 weather.yahooapis.com | grep -c "(0 received)|(unknown host)"`

if ping -c1 weather.yahooapis.com >/dev/null;
then
	echo "Connection established!";
else
	echo "No connection!";
	exit 1;
fi

TIME_TO_SLEEP=`cat config.ini`

while true; do 
	lwp-request "weather.yahooapis.com/forecastrss?w=834463&u=c" | grep -A1 "Current" | tail -n 1 | cut -d '<' -f1; 
	sleep $TIME_TO_SLEEP; 
done;


